### ISSUE TITLE
Section showcasing integrations of dayjs

### ISSUE THREAD

**Issue by devshawn** [iamkun/dayjs#103]
Hi, huge fan of this library! Currently working on moving different projects from moment to dayjs.

I'm wondering if it would be nice to have a section on the README showing projects/integrations that utilize dayjs, mainly ways in which people can start using dayjs? I use React and have been working on the [react-dayjs](https://github.com/devshawn/react-dayjs) module for displaying dates in React using dayjs, and I saw there is someone working on an [dayjs angular pipes](https://www.npmjs.com/package/ngx-dayjs) module as well. 

Just an idea, thanks for the project! :)

**Comment by iamkun** [comment]
First of all, nice work with this! 

Since Day.js is a pure, tiny date library, it should works perfectly with all JS frameworks with no additional configuration. All we have to do is `import dayjs` and use it.

Still a showcase containing projects like react-dayjs, ngx-dayjs is a great idea. It's more like a framework's preferred API or syntax, and maybe easy to understand for those frameworks users.

We will think about it. And discussions are welcome.

**Comment by devshawn** [comment]
Thanks, @iamkun!

Agreed, it should work perfectly and is a great option -- I mainly made react-dayjs for the simplicity and ease-of-use for react developers so they don't have to make their own react component to do it. 

Thanks for your thoughts! 👍

**Comment by iamkun** [comment]
seems we don't need this at this time
