### ISSUE TITLE
Constructor with custom format

### ISSUE THREAD

**Issue by Imperat** [iamkun/dayjs#136]
moment.js has wide usable feature to make date from custom strings. For example:
`moment('2018-02-01', 'YYYY-DD-MM')`
or
`moment('02-2018-01', 'DD-YYYY-MM');`

Do we want to support this feature in our core? I'm not sure how to implement it in minimalist way, but I think we need to rewrite .format function somehow to avoid copy-paste of code. If you will be agree, guys, that we need to have this feature - I'll think about it.

**Comment by iamkun** [comment]
maybe some one need this feature, but still I recommend using ISO date format always.

**Comment by mnewmedia** [comment]
@iamkun Yep using ISO would format is a great advice, but some (me :D) have to deal with data from other sources which doesn't support the ISO date format.

**Comment by atomfrede** [comment]
Is someone working in that feature (if not I can try to do it), as I try to get rid of moment in https://www.jhipster.tech/ which is part of the react validation lib which relies on that specific moment api (`moment('2018-02-01', 'YYYY-DD-MM')`) to check if the date entered in a component is a valid date (and conforms the specified format).

**Comment by iamkun** [comment]
@atomfrede That would be nice. Besides, a plugin might be better. e.g. `customFormatParser`

**Comment by atomfrede** [comment]
@iamkun :heavy_check_mark: I will try to build one.

**Comment by iamkun** [comment]
@atomfrede Cheers

**Comment by alanaasmaa** [comment]
I also started using this till i found out that i can't parse back to date from my format.

**Comment by prantlf** [comment]
There are two usage scenarios for parsing in my application:

1. Construct `dayjs` from a persistent storage. The strings come in the fixed ISO format. No problem.
2. Construct `dayjs` from the date picker output. The strings come in a customizable user-specific format. Big problem.

The second scenario needs a custom parsing.

@atomfrede, thanks, you'll save me time to implement the `customFormatParser` myself :-) After the three PRs I posted, this is the last feature that I need to start using Day.js instead of Moment.js.

**Comment by dmydry** [comment]
Hey guys! @iamkun thanks for so lightweight lib.
@prantlf great and so wanted feature! waiting for your pr to be approved and merged.

**Comment by robsonsobral** [comment]
Sometimes, the date is user provided.

Also, is pretty strange that both '2005-02-18' and '02-18-2018' are valid dates.

**Comment by iwantwin** [comment]
I'm dying to use this library instead of momentjs! But I really need this feature to be implemented before I can switch. Bundle size & tree shaking means a lot at the moment.. ;)

If anyone is working on it, let me know if and how I can help :)

**Comment by prantlf** [comment]
@iwantwin, if you want to test the current functionality, you can pull #340 to your fork. Or you can install the NPM module  [`dayjs-ext`](https://github.com/prantlf/dayjs#dayjs-extended) instead of `dayjs` to get the functionality easier to your project.

The current version of the [CustomParseFormat
](https://github.com/prantlf/dayjs/blob/combined/docs/en/Plugin.md#customparseformat) plugin, supports only numeric placeholders like "YYYY", "MM" or "DD". It does not support the textual (and thus localizable) ones like "MMM" or "MMMM". If you need it, you might consider adding it to my change.

**Comment by dmydry** [comment]
@iwantwin I'm currently using the dayjs-ext in production and it works perfectly.
@prantlf thanks by the way!

**Comment by iamkun** [comment]
:tada: CustomParseFormat plugin is supported and included in version 1.8.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/dayjs)
- [GitHub release](https://github.com/iamkun/dayjs/releases/tag/v1.8.0)
