### ISSUE TITLE
Request - Format duration days as more than 24h

### ISSUE THREAD

**Issue by N0ps32** [iamkun/dayjs#1376]
I have a duration that is always going to be max. 48h. I'd like to format my Duration like this: "47h 45m 20s". I haven't found a way to do that currently other than using asHours().toFixed() which isn't ideal. Would be awesome if there was a way to do that using the format() method

**Comment by iamkun** [comment]
Sorry, we have no plan to support this.

**Comment by bornova** [comment]
@N0ps32,
Sorry if I am not understanding your question correctly but couldn't you get the days from a duration, convert it to hours, and then add that to the hours of the duration?   Something like this:

[https://runkit.com/6022b36c23da0600130851a0/6022b36c7614ed001ad11853](https://runkit.com/6022b36c23da0600130851a0/6022b36c7614ed001ad11853)

I used milliseconds for duration since I don't know how you are defining your duration.

**Comment by N0ps32** [comment]
> @N0ps32,
> Sorry if I am not understanding your question correctly but couldn't you get the days from a duration, convert it to hours, and then add that to the hours of the duration? Something like this:
> 
> https://runkit.com/6022b36c23da0600130851a0/6022b36c7614ed001ad11853
> 
> I used milliseconds for duration since I don't know how you are defining your duration.

asHours().toFixed() returns the same result as your calculation. I wanted to suggest adding a new combination of letters for  format() to allow formatting of hours > 24h something like: HHHH. It isn't uncommon behavior to represent 2-3 days as hours so I think the ability to do it directly with format() would be better than having to calculate it manually.
