### ISSUE TITLE
format('Do') returned '20o' not '20th'

### ISSUE THREAD

**Issue by mandaputtra** [iamkun/dayjs#1542]
**Describe the bug**
When using `dayjs().format('Do')`  it returns `20o` not `20th`. Check it here https://codesandbox.io/s/use-do-on-dayjs-bugs-mwowt?file=/src/index.js. Docs https://day.js.org/docs/en/parse/string-format

**Expected behavior**
It should return `20th`

**Information**
 - Day.js Version latest
 - OS: Linux
 - Browser Latest
 - Time zone: GMT+7

**I'm willing to make a pull request if it was clearly a bug**

**Comment by bornova** [comment]
Hi @mandaputtra,
List of all available formats are documented here: https://day.js.org/docs/en/display/format
And if you scroll down, you will notice that it states "Other formats ( dependent [AdvancedFormat](https://day.js.org/docs/en/plugin/advanced-format) plugin )"

Turns out the `Do` format you are after requires the `AdvancedFormat` plugin to work.  Here is an example:
https://runkit.com/60d016828f113f001ab466e2/60d016998f113f001ab466ee

**Comment by bornova** [comment]
Hi @mandaputtra,
List of all available formats are documented here: https://day.js.org/docs/en/display/format
And if you scroll down, you will notice that it states "Other formats ( dependent AdvancedFormat plugin )"

Looks like the Do format you are after requires the AdvancedFormat plugin to work. Here is an example:
https://runkit.com/60d016828f113f001ab466e2/60d016998f113f001ab466ee

**Comment by mandaputtra** [comment]
Ooow my bad! Thanks for letting me know.
