### ISSUE TITLE
How would I integrate plugins in a Next.js project?

### ISSUE THREAD

**Issue by simplenotezy** [iamkun/dayjs#1551]
I can integate it just fine using 

     import dayjs from 'dayjs';

However, when trying to require plugins, it get's trickier:

```
import dayjs from 'dayjs';
import dayjsCalendar from 'dayjs-calendar';
dayjs.extend(dayjsCalendar);
```

Will fail with: 

    ReferenceError: dayjs is not defined

![image](https://user-images.githubusercontent.com/3786627/123380163-6961f880-d58f-11eb-9b63-1fb0afd7c34a.png)

**Comment by addisonElliott** [comment]
This isn't a bug with Day.js.

If you use Day.js' calendar plugin, your code works fine. See here: https://day.js.org/docs/en/plugin/calendar

The problem is the `dayjs-calendar` package which hasn't been updated in 3 years. Here's the bug: https://github.com/charleslo1/dayjs-calendar/blob/master/src/calendar.js#L14

The day.js module isn't imported and causes that error.

**Comment by iamkun** [comment]
thanks @addisonElliott 

close because not dayjs bug.

Please use our official plugin https://day.js.org/docs/en/plugin/calendar
