### ISSUE TITLE
Day.js  parse ISO 8601 with error . Day.js Version 1.10.7 

### ISSUE THREAD

**Issue by ricpar123** [iamkun/dayjs#1723]
**Describe the bug**

**Expected behavior**

**Information**
 - Day.js Version [e.g. v1.0.0]
 - Browser [e.g. chrome 62]
 - Time zone: [e.g. GMT-07:00 DST (Pacific Daylight Time)]

**Comment by ricpar123** [comment]
Get a date from mongoDB as '2021-09-08T00:00:00:000Z' and format it with day.js, as dayjs('mongoDate').format('DD/MM/YYYY'), the result is '07/09/2021', one day less. Why?

**Comment by monzilnepali** [comment]
@ricpar123 `2021-09-08T00:00:00:000Z` is UTC time and the format will convert the date to local time. so if there is a day difference between your local time(PST) and UTC, then it will return one day less. 
If you just want to format without timezone issues, then use UTC mode.
`daysjs.utc(date).format('DD/MM/YYYY)`

**Comment by ricpar123** [comment]
ok....thank you very much!

**Comment by monzilnepali** [comment]
@ricpar123 close this issue

**Comment by ryancwalsh** [comment]
Wow, if this is true, I feel like the current implementation of the `format` function violates the Principle of Least Surprise.

And the docs at https://day.js.org/docs/en/display/format don't even warn about this.

I feel like the most reasonable expectation is that if someones passes a date with a specific time zone (such as UTC, as @ricpar123 did with '2021-09-08T00:00:00:000Z'), then the formatting would stay in that time zone rather than be client-specific.
