### ISSUE TITLE
MM > 12 and DD > 31 do not result in invalid date

### ISSUE THREAD

**Issue by GamerBene19** [iamkun/dayjs#1935]
**Describe the bug**
Executing `dayjs("2022-99-99", "YYYY-MM-DD")` does result in a valid date.

**Expected behavior**
Date should be invalid

**Information**
 - Day.js Version: `1.11.2`
 - OS: `Arch, up to date`
 - Browser: Firefox version `101.0`
 - Time zone: CEST

The issue likely affects other possible format strings aswell (e.g. seconds > 60 (in the context of timestamps)), but I have only experienced and tested it with the above format.

**Comment by BePo65** [comment]
That is not an error, but by design (see my [comments](https://github.com/iamkun/dayjs/pull/1914#issuecomment-1139888043) in pr #1914).

If you want the result to be 'Invalid Date' then use the strict option ('true' as 3rd parameter).  
Without strict mode, dayjs behaves like the javascript Date object using 'overflow'.

**Comment by GamerBene19** [comment]
I see. Sorry, for the unnecessary issue ^^
