### ISSUE TITLE
Daisy chain substraction not working

### ISSUE THREAD

**Issue by Mitrajit** [iamkun/dayjs#2556]
**Describe the bug**
On using subtract twice it is not subtracting. Same for node and bun. I wrote the code in typescript. Shifting to moment.js
![Screenshot 2024-01-15 at 9 42 27 PM](https://github.com/iamkun/dayjs/assets/55190574/3aec0f16-6da7-4790-8b0f-0bb38a51e066)

**Expected behavior**
![Screenshot 2024-01-15 at 9 45 47 PM](https://github.com/iamkun/dayjs/assets/55190574/0d88d8a4-5c4f-4956-8d84-47191e11a13b)

**Information**
 - Day.js Version "dayjs": "^1.11.10",
 - OS: macOS
 - Bun version: 1.0.4
 - Time zone: IST

**Comment by rpeng** [comment]
DayJS is immutable unlike moment, so methods such as `add` and `subtract` will not modify the original but instead return a modified clone. You'll have to assign the subtraction result to a new variable to make use of it.

**Comment by Igvir** [comment]
Shouldn't this issue be closed?

**Comment by buza-me** [comment]
> Shouldn't this issue be closed?

It  should, but people think that a bug tracker === Reddit. They open issues before reading the docs and then never even bother to close them. I'm just trying to get an understanding how well Dayjs vs Date-fns is doing in terms of support, and this is incredibly annoying. How many of the issues are real issues? Will the project owner abandon it because he grows tired of this bs? It looks like iamkun is not very active here, a lot of old PRs and old issues but I cba digging through to find out if they are just irrelevant.
