### ISSUE TITLE
In Safari, parsing "2024 7 1" with format "YYYY M D" fails, but "2024/7/1" with format "YYYY/M/D" succeeds

### ISSUE THREAD

**Issue by csterritt** [iamkun/dayjs#2570]
**Describe the bug**
The following code produces an invalid date on Safari:

  const year = 2024
  const month = 7
  const day = 1
  const str = `${year} ${month} ${day}`
  date = dayjs(str, ['YYYY MM D', 'YYYY M D', 'YYYY MM DD', 'YYYY M DD'])
  if (date?.isValid()) {
     // ... works on non-Safari browsers
  } else {
     // ... fails on Safari
  }

However, changing the delimiter from space to slash works:
  const str = `${year}/${month}/${day}`
  date = dayjs(str, ['YYYY/MM/D', 'YYYY/M/D', 'YYYY/MM/DD', 'YYYY/M/DD'])
  // This date is valid on all browsers

**Expected behavior**
Proper parsing no matter if the delimiter is space or slash.

**Information**
 - Day.js Version 1.11.10
 - OS: macOS Sonoma 14.3
 - Browser Safari 17.3
 - Time zone: GMT-05:00 EST

**Comment by buza-me** [comment]
Hey @csterritt . It works in Chrome because ```new Date('2024 7 1')``` works in Chrome. But it does not work in Safari. Only ```/``` and ```-``` symbols are specified as delimiters in the spec afaik, so Safari devs didn't feel like implementing spaces. This is a browser "bug" that you are reporting. Dayjs have tried to make a consistent default behavior by using a regex parser which recognizes ```-/``` delimiters. After it fails to parse space separated input, it defaults to ```new Date(input)``` call.

By default Dayjs does not accept format strings/arrays, like you passed as a second argument.

The detailed instructions how to resolve your issue can be found here:
https://day.js.org/docs/en/parse/string-format

Pay extra attention to the yellow/orange blockquotes in the documentation.

**Comment by csterritt** [comment]
@buza-me Thanks -- I appreciate your response.

However, I was following the "string-format" documentation you linked to, and I'd already done the `dayjs.extend(customParseFormat)` (per the yellow/orange block quote in the documentation), so the parse *should* work, even on Safari -- right?

If not, either the documentation should specify that only some format strings work, or the code should be fixed to match the documentation.

**Comment by csterritt** [comment]
This is a "works as designed" thing, so if someone else wants to add space as a delimiter it should probably be another issue.

**Comment by buza-me** [comment]
> This is a "works as designed" thing, so if someone else wants to add space as a delimiter it should probably be another issue.

It should work in Safari if you extended it properly, I think. I'm a lazy ass so I ask ChatGPT for Regex explanations. Following is the ```formattingTokens``` Regex from the plugin code - https://github.com/iamkun/dayjs/blob/dev/src/plugin/customParseFormat/index.js
<img width="459" alt="image" src="https://github.com/iamkun/dayjs/assets/45733786/96c687b4-4f76-4d28-a2b2-0641f267608c">
The parser function splits the format string into "filler/padding" square brackets as I get it, separators that include spaces, and expressions listed in the table here:
https://day.js.org/docs/en/parse/string-format#list-of-all-available-parsing-tokens

Then it iterates like this:
```
function (input) {
    const time = {}
    for (let i = 0, start = 0; i < length; i += 1) {
      const token = array[i]
      if (typeof token === 'string') {
        start += token.length
      } else {
        const { regex, parser } = token
        const part = input.slice(start)
        const match = regex.exec(part)
        const value = match[0]
        parser.call(time, value)
        input = input.replace(value, '')
      }
    }
    correctHours(time)
    return time
  }
```
Type of token equals to 'string' if the token is a separator, including space, or if it is a "padding" enclosed into square brackets, as I understand. So it should work in Safari, because it is not using a fallback to ```new Date(input)```.
```
console.log(parseFormattedInput('2024 7 1', 'YYYY M D')); // => Mon Jul 01 2024 00:00:00 GMT+0300 (Eastern European Summer Time)
console.log(parseFormattedInput('qqqqq 2024 qqqqq 7 1', '[12345] YYYY [12345] M D')); // => Mon Jul 01 2024 00:00:00 GMT+0300 (Eastern European Summer Time)
```

**Comment by buza-me** [comment]
here is the full snippet if you want to test it:
https://pastebin.com/Z7q5J3ah
That is basically the plugin code copy pasta
