### ISSUE TITLE
Validating date using a locale

### ISSUE THREAD

**Issue by robsonsobral** [iamkun/dayjs#362]
Hi!

Is there a way to validated a date using a locale? Something like `dayjs('15/10/2018', {locale: 'pt-br'}).isValid()`?

Thank you!

**Comment by naulacambra** [comment]
That exactly code doesn't work? 

According to [this](https://github.com/iamkun/dayjs/blob/master/docs/en/I18n.md#changing-locales-locally), it should.

**Comment by robsonsobral** [comment]
No, it doesn't. I tested yesterday withe the last version available.

**Comment by naulacambra** [comment]
Ok, checking the code, it seems that the locale settings are only useful for display. Meaning that you need to work with standard formats.

``` javascript
dayjs('15/10/2018', {locale: 'pt-br'}).isValid(); // false
dayjs('10/15/2018', {locale: 'pt-br'}).isValid(); // true
dayjs('10/15/2018', {locale: 'pt-br'}).format('DD/MM/YYYY'); // 15/10/2018
```

**Comment by robsonsobral** [comment]
So we have a problem, because `10/15/2018` is a localized date. Is strange to not accept localized dates, with one exception [not mentioned on docs](https://github.com/iamkun/dayjs/blob/master/docs/en/API-reference.md#constructor-dayjsexisting-string--number--date--dayjs). I thought the lib only accepts ISO dates.

**Comment by naulacambra** [comment]
`10/15/2018` has a format accepted by native `Date` class.

``` javascript
new Date('10/15/2018') // Mon Oct 15 2018 00:00:00 GMT+0200 (hora de verano de Europa central)
```

Even so, MDN [warns about using this format](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#Fall-back_to_implementation-specific_date_formats), it will work but as local, since is not an standard format.

**Comment by robsonsobral** [comment]
Good point, but is still risky.

Could we have at least a parameter or config to accept only ISO?

**Comment by robsonsobral** [comment]
Exactly. How can I make sure if the date inserted by an user is real if both formats are valid? [136](https://github.com/iamkun/dayjs/issues/136) can help too.

**Comment by naulacambra** [comment]
I didn't saw the #340 PR. You'll have to wait until is merged. I hope in a few weeks

**Comment by prantlf** [comment]
I [added](881e66c10c79fe8e33c2309cb891ecf1a1fe52e8) parsing of [localizable formats "Moment.js style"](https://github.com/prantlf/dayjs/blob/combined/docs/en/Plugin.md#localizableformat) to [LocalizableFormat](https://github.com/prantlf/dayjs/blob/combined/docs/en/Plugin.md#localizableformat) (#305), so that it can be combined with [CustomParseFormat](https://github.com/prantlf/dayjs/blob/combined/docs/en/Plugin.md#customparseformat) (#340). Only the non-string format tokens L, LT and LTS are recognized in parsing for the time being.

This is available only in [`dayjs-ext`](https://www.npmjs.com/package/dayjs-ext), as long as these plugins are not accepted to `dayjs`. I needed to extend the core package with `Utils.getLocale` to be able to implement the localizable format parsing. Both packages are need for the complete unit test too.

```js
import dayjs from 'dayjs-ext'

import ptBr from 'dayjs-ext/locale/pt-br'
dayjs.locale(ptBr)

import customParseFormat from 'dayjs-ext/plugin/customParseFormat'
import localizableFormat from 'dayjs-ext/plugin/localizableFormat'
dayjs.extend(customParseFormat)
dayjs.extend(localizableFormat)

// Use the format "DD/MM/YYYY" defined in the pt-br locale
dayjs('15/10/2018', { format: 'L' }).isValid()
```

However, you should not overestimate the quality of the validation. You will be able to catch nonsense like `MM=15`, if the user exchanges values of `DD` with `MM`. But you won't be able to ensure, that `DD` and `MM` will be set, as the user intended from an input like `02/05/2018`. The user will still have to be aware of the format like `DD/MM/YYYY`.

**Comment by robsonsobral** [comment]
@prantlf , please, what the `L`, `LT`and `LTS` mean?

**Comment by robsonsobral** [comment]
Thank you! I didn't know this standard.

**Comment by iamkun** [comment]
From v1.8.7, you could check like this
```
import 'dayjs/locale/es'
import customParseFormat from 'dayjs/plugin/customParseFormat'
dayjs.extend(customParseFormat)

dayjs('2018 Enero 15', 'YYYY MMMM DD', 'es').isValid()
```
