### ISSUE TITLE
format month error?

### ISSUE THREAD

**Issue by oklxq** [iamkun/dayjs#398]
date:2018-10-31
```js
dayjs().set('month',10).set('date',1).format('MM-DD');
// except: 11-01
// got: 12-01
```
![b73d2cf1-9b73-402c-8982-bca85c810f92](https://user-images.githubusercontent.com/12524014/47764745-81f7b300-dd01-11e8-99ac-34c545eabbd8.jpg)

**Comment by prantlf** [comment]
`Day.js` follows the behaviour of the native `Date` here. `set(month, 10)` does not "swap" the month number only. It "moves" the current month to November and if the day does not exist, it goes further to December.

If the day-in-month date exists in the other month, the specified month number stays:

```
> d('2018-10-21 12:00').format('MM-DD')
'10-21'
> d('2018-10-21 12:00').set('month', 10).format('MM-DD')
'11-21'
```

If the day-in-month date does not exist in the other month (November has only 30 days here), the specified month number will shift (by 1 day here):

```
> d('2018-10-31 12:00').format('MM-DD')
'10-31'
> d('2018-10-31 12:00').set('month', 10).format('MM-DD')
'12-01'
```

If `Day.js` (or `Date`, actually) did not do it, the date would become invalid. What behaviour would you expect? Subtracting a day or two, so that you would still stay in the same month instead?

**Comment by iamkun** [comment]
duplicate  #399
