### ISSUE TITLE
DayJS format mm-dd-yyyy does not work on chrome but works on Firefox 

### ISSUE THREAD

**Issue by fayazara** [iamkun/dayjs#417]
The format 'mm-dd-yyyy' does not work on Firefox, but works properly on Chrome.

Here is a example of the Bug - https://codepen.io/fayazara/pen/eQRPNx

Expected result - Supposed to print 'Tuesday'
Actual result - Blank

Workaround - As per DayJS documentation, the format is supposed to be YYYY-mm-dd, changing it to this format works out well in Firefox. If so, why does this work on Chrome?

**Comment by naulacambra** [comment]
The issue here is not the library itself, but how browsers work with native js `Date` class.

DayJS depends heavily on native `Date`. In Chrome, when you create a new Date with the date in your example, this is the result
``` javascript
new Date('11-08-2018')
Thu Nov 08 2018 00:00:00 GMT+0100 (hora estándar de Europa central)
```

By other hand, in Firefox, this is the result
``` javascript
new Date('11-08-2018')
Invalid Date
```

I'm not sure why this happens. At the [MDN Date documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) there is not explicit difference about how differents browser treat date other than this note

> Note: parsing of date strings with the Date constructor (and Date.parse, they are equivalent) is strongly discouraged due to browser differences and inconsistencies. Support for RFC 2822 format strings is by convention only. Support for ISO 8601 formats differs in that date-only strings (e.g. "1970-01-01") are treated as UTC, not local.

My recommendation would be, try to work with ISO format, and everything will work much more smoothly.

**Comment by loveonelong** [comment]
Maybe we can create some plugins transform date to ISO format for compatibility with different browsers.

**Comment by suspectpart** [comment]
I think this is not a bug. As @naulacambra pointed out, it is discouraged to parse date strings through the constructor anyway. In dayjs, there are already a little too many ways to parse a date in my opinion.

```javascript
const parseDate = (date) => {
  let reg
  if (date === null) return new Date(NaN) // Treat null as an invalid date
  if (Utils.isUndefined(date)) return new Date()
  if (date instanceof Date) return date
  // eslint-disable-next-line no-cond-assign
  if ((typeof date === 'string')
    && (/.*[^Z]$/i.test(date)) // looking for a better way
    && (reg = date.match(C.REGEX_PARSE))) {
    // 2018-08-08 or 20180808
    return new Date(
      reg[1], reg[2] - 1, reg[3] || 1,
      reg[5] || 0, reg[6] || 0, reg[7] || 0, reg[8] || 0
    )
  }
  return new Date(date) // timestamp
}
```

So, 

- `undefined` (which is the empty constructor) is `now`,
- existing `Date` instances get wrapped, 
- `null` is an invalid date (other than Browsers that interpret null as `1970-01-01T00:00:00.000Z),
- ISO strings like `2018-08-15` or `20180815` get interpreted as such
- Integers like `1549136977856` get interpreted as unix timestamps

But there also hides a hidden 'feature' which is kind of misleading from the comment `return new Date(date) // timestamp` which implies only timestamps go here. If you pass a date as `08-01-2018` (the opener for this issue) or even `'Sat Feb 02 2019 20:41:56 GMT+0100'`, you fall through (as the regex doesn't catch it) to the default constructor of `Date`, that is why this bug is happening. And we also rely on this fall through for every other invalid value like `[]`, `{}`, `function(){}` and so on. Interestingly, in Chrome it would even be possible to pass a lambda returning a date string here and get a valid instance of `Date` (try it in the developer console: `new Date(() => "2018-01-01")`).  

So we should carefully consider what the constructor actually allows implicitly or what should go into explicit builder functions like

`dayjs.fromTimestamp(1549136977856)`
`dayjs.parseFormat("dd-mm-YYYY")`
`dayjs.fromISOString("2018-01-01T13:52:54Z")`

**Comment by xxyuk** [comment]
@suspectpart 
I think DayJs's `CustomParseFormat` plugin is just what you are looking for.

**Comment by iamkun** [comment]
Use `CustomParseFormat` plugin  to deal with custom date formats

**Comment by suspectpart** [comment]
@iamkun @xxyuk 

Should we still refactor this bit of code?

> ```js
> const parseDate = (date) => {
>   let reg
>   if (date === null) return new Date(NaN) // Treat null as an invalid date
>   if (Utils.isUndefined(date)) return new Date()
>   if (date instanceof Date) return date
>   // eslint-disable-next-line no-cond-assign
>   if ((typeof date === 'string')
>     && (/.*[^Z]$/i.test(date)) // looking for a better way
>     && (reg = date.match(C.REGEX_PARSE))) {
>     // 2018-08-08 or 20180808
>     return new Date(
>       reg[1], reg[2] - 1, reg[3] || 1,
>       reg[5] || 0, reg[6] || 0, reg[7] || 0, reg[8] || 0
>     )
>   }
>   return new Date(date) // timestamp
> }
> ```

There are several issues with that implementation:
-  `// eslint-disable-next-line no-cond-assign` points out the use of an assignment expression which I also think is not quite straightforward. The `let reg` in the first line is only needed if that assignment is being made, but in same cases the code returns before reg is even needed, so this could be refactored
- `return new Date(date) // timestamp` is misleading as every other case that is not explicitly handled will also end up here, not just the timestamps. So e.g. `parseDate(function(){})`,  `parseDate({})`, `parseDate(() => "2018-01-01")` [that one even works in Chrome] or `parseDate('Sat Feb 02 2019 20:41:56 GMT+0100')` will fall through to the constructor of `Date` as well.
- There is a hint that `// looking for a better way` which also implies that the first regex test might be refactored (what exactly is the point of that test, anyway?).

If you want to, I could create a PR and clean that stuff up. Maybe create a new issue for that?

**Comment by iamkun** [comment]
@suspectpart Thanks, and pr welcome.

Maybe it's better to have a discussion upon your PR, since I may not fully understand your comment above.
