### ISSUE TITLE
Plugin import in angular project throws error 'no default export'

### ISSUE THREAD

**Issue by BingeCode** [iamkun/dayjs#613]
**Describe the bug**
Plugin import throws error in angular project / browser
`dayjs__WEBPACK_IMPORTED_MODULE_5__(...).month(...).startOf(...).weekday is not a function`

**Expected behavior**
I can use most dayjs functions just fine with `import * as dayjs from 'dayjs'`.

But when I need to use plugins, I import with `import * as weekday from 'dayjs/plugin/weekday`, it throws me this error in the browser - even though the compiler recognises the function weekday just fine:

`dayjs__WEBPACK_IMPORTED_MODULE_5__(...).month(...).startOf(...).weekday is not a function`

![image](https://user-images.githubusercontent.com/48513535/59253781-3dd17700-8c2f-11e9-9c02-de2d97df229d.png)

Trying to import the weekday plugin with `import weekday from 'dayjs/plugin/weekday';
` throws compiler error `Module '"C:/.../node_modules/dayjs/plugin/weekday"' has no default export.`

OR `import { weekday } from 'dayjs/plugin/weekday';
` throws compiler error `Module '"C:/.../node_modules/dayjs/plugin/weekday"' has no exported member`

**Information**
 - Day.js Version 1.8.14
 - OS: Win 10 / Angular Typescript Project
 - Browser Chrome 74

**Comment by iamkun** [comment]
Please provide a test repo.

**Comment by thomascsd** [comment]
Use ``dayjs.extend``, see [doc](https://github.com/iamkun/dayjs/blob/dev/docs/en/Plugin.md)

```javascript
import * as dayjs from 'dayjs';
import * as weekday from 'dayjs/plugin/weekday';
dayjs.extend(weekday);
```

**Comment by JustFly1984** [comment]
Ok, here is the thing, we have same or equal issues with gatsby, which is related to:
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-typescript/README.md

Which is described as:
This plugin uses `babel-plugin-transform-typescript` to transpile TypeScript. It does not do type checking. Also since the TypeScript compiler is not involved, the following applies:

Does not support namespaces. Workaround: Move to using file exports, or migrate to using the module { } syntax instead.

Does not support const enums because those require type information to compile. Workaround: Remove the const, which makes it available at runtime.

Does not support export = and import =, because those cannot be compiled to ES.next. Workaround: Convert to using export default and export const, and import x, {y} from "z".

https://babeljs.io/docs/en/babel-plugin-transform-typescript.html

**Comment by JustFly1984** [comment]
the only workaround which works, is to setup tsconfig with
```
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
```

**Comment by iamkun** [comment]
https://day.js.org/docs/en/installation/typescript this might help

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
