### ISSUE TITLE
Formatting ordinal dates doesn't work

### ISSUE THREAD

**Issue by nelstrom** [iamkun/dayjs#770]
**Describe the bug**
The `Do` formatting option from the [AdvancedFormat](https://github.com/iamkun/dayjs/blob/dev/docs/en/Plugin.md#advancedformat) plugin doesn't appear to work since upgrading to [v1.8.19](https://github.com/iamkun/dayjs/releases/tag/v1.8.19)

**Expected behavior**

Given this code:

```js
import advancedFormat from 'dayjs/plugin/advancedFormat'
dayjs.extend(advancedFormat)
dayjs('2020-01-06').format('Do MMM YYYY')
```

I expect the output: `6th Jan 2020`, but instead I'm seeing `6o Jan 2020`. This seemed to work fine in `v1.8.18`, but appears to be broken since upgrading to `v1.8.19`.

**Information**
 - Day.js Version: 1.8.19

This regression was picked up by our test suite, so I haven't included a Browser.

**Comment by nelstrom** [comment]
Closing this issue, because the problem appears to have been caused by one of the other dependencies in our app. My apologies for the noise.

**Comment by hutber** [comment]
@nelstrom sorry, care to elaborate? Its not working for myself either.

**Comment by iamkun** [comment]
@hutber any demo code, pls

**Comment by hutber** [comment]
Thanks @iamkun the problem was that the advancedFormat plugin was not included.
`import advancedFormat from "dayjs/plugin/advancedFormat";`
I am not sure if this has caught anybody else out... sorry to use your time up.
I think I would have found this information in the table very helpful! :)
![image](https://user-images.githubusercontent.com/1344898/97897650-b0645a80-1d2e-11eb-95b8-93a8f6cd9bf2.png)

**Comment by BinarySpike** [comment]
`import advancedFormat from "dayjs";` doesn't seem to be working.

**Comment by 5ero** [comment]
Don't forget to add `dayjs.extend(advancedFormat)`
